### ISSUE TITLE
Menu bar doesn't follow dark/light theme on Windows

### ISSUE THREAD

**Issue by dzhou121** [tauri-apps/muda#97]
The window title bar follows dark/light them on Windows nicely but not the menu bar.

Is it possible to do or a limitation of win32 api?

**Comment by dhan2325** [comment]
I saw the linked PR was merged, but I wasn't sure if the feature was added to to v1.* or if this is to be included in v2. I'm currently working in v1 now, and I'm finding that on Windows, even with both my OS and my window theme set to dark mode, while the title bar theme seems to behave correctly, my menu bar is consistently showing up in light mode colors.

If someone could point me to any configs I might have missed or if this feature is available in v1 at all or if there's a solid workaround in v1, I'd greatly appreciate it.

**Comment by amrbashir** [comment]
That's for v2, v1 will stay as is

**Comment by dhan2325** [comment]
Is it included in the beta release of V2 that was announced earlier this month?

**Comment by amrbashir** [comment]
yeah, it is included
